[package]
name = "amadeo-ecs"
description = "Archetype-based entity component system for the Amadeo engine."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
amadeo-core.workspace = true

[lints]
workspace = true
